Homework02
Maziluiulia/test-repo pull request #2
Opened 2022-12-16 18:30 UTC by Maziluiulia

homework02

2022-12-16 19:02 UTC, Maziluiulia commented
Homework 02.
Accidently added homework 01 also

2022-12-17 15:54 UTC, klymenok requested changes
Please, remove files that is not related to the homework.

Also, it would be better in your solution to check first if value is digit since words or phrases can contain some symbols (`', -`), and those symbols won't be recognized as letters during isalpha() check and you will get an error during the `int(a)` operation.

2022-12-18 20:02 UTC, klymenok approved these changes
Looks good. Check my comment. You can improve your code before you merge the PR, if you want

2022-12-18 20:02 UTC, klymenok commented on home02.py
> +if (a.isdigit()) and (int(a) % 2 == 0):
There is no need to use parentheses around the condition. You can use it like this: `if a.isdigit()) and (int(a) % 2 == 0:`

2022-12-18 20:02 UTC, klymenok commented on home02.py
> +    print("It is text ")
It would be much better to format this text in one line, like this: `print(f'It is a text. Its length is {len(a)}')`

2022-12-28 20:13 UTC, merged